name: dz4
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/slimbdey/dart_dz4

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0
